"""3.0.1-Update

Revision ID: bb00b7dc1c67
Revises: 970a2316abb6
Create Date: 2025-07-14 14:12:25.888132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb00b7dc1c67'
down_revision: Union[str, Sequence[str], None] = '970a2316abb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('go_master', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('go_master', 'test')
    # ### end Alembic commands ###
