"""create KDC module

Revision ID: d489a4844bac
Revises: d139d3e0b0df
Create Date: 2026-02-06 03:11:30.597781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd489a4844bac'
down_revision: Union[str, Sequence[str], None] = 'd139d3e0b0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kdc_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('asset', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'data_source', 'asset', name='uq_kdc_asset_identity')
    )
    op.create_index('ix_kdc_assets_asset', 'kdc_assets', ['asset'], unique=False)
    op.create_index('ix_kdc_assets_data_source', 'kdc_assets', ['data_source'], unique=False)
    op.create_index('ix_kdc_assets_source_system', 'kdc_assets', ['source_system'], unique=False)
    op.create_table('kdc_scan_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('kds_root', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='kdc_scan_status_enum', create_constraint=True), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kdc_scan_runs_started_at', 'kdc_scan_runs', ['started_at'], unique=False)
    op.create_index('ix_kdc_scan_runs_status', 'kdc_scan_runs', ['status'], unique=False)
    op.create_table('kdc_asset_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('release', sa.String(length=120), nullable=False),
    sa.Column('assembly', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', 'FAILED', 'STAGED', name='kdc_asset_status_enum', create_constraint=True), nullable=False),
    sa.Column('base_path', sa.Text(), nullable=False),
    sa.Column('path_pattern', sa.Text(), nullable=True),
    sa.Column('partitioning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('manifest_path', sa.Text(), nullable=True),
    sa.Column('manifest_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(assembly) > 0', name='ck_kdc_asset_versions_assembly'),
    sa.ForeignKeyConstraint(['asset_id'], ['kdc_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'release', 'assembly', 'manifest_hash', name='uq_kdc_asset_version_identity_by_manifest')
    )
    op.create_index('ix_kdc_asset_versions_assembly', 'kdc_asset_versions', ['assembly'], unique=False)
    op.create_index('ix_kdc_asset_versions_asset_release', 'kdc_asset_versions', ['asset_id', 'release'], unique=False)
    op.create_index('ix_kdc_asset_versions_status', 'kdc_asset_versions', ['status'], unique=False)
    op.create_table('kdc_lineages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_version_id', sa.Integer(), nullable=False),
    sa.Column('dtp_name', sa.String(length=200), nullable=True),
    sa.Column('dtp_version', sa.String(length=60), nullable=True),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters_hash', sa.String(length=64), nullable=True),
    sa.Column('inputs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['kdc_asset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_version_id')
    )
    op.create_index('ix_kdc_lineages_dtp_name', 'kdc_lineages', ['dtp_name'], unique=False)
    op.create_index('ix_kdc_lineages_parameters_hash', 'kdc_lineages', ['parameters_hash'], unique=False)
    op.create_table('kdc_schema_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_version_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=120), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_field', sa.String(length=200), nullable=True),
    sa.Column('semantics', sa.String(length=200), nullable=True),
    sa.Column('units', sa.String(length=80), nullable=True),
    sa.Column('enum_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_link_key', sa.Boolean(), nullable=False),
    sa.Column('links_to_entity', sa.String(length=100), nullable=True),
    sa.Column('db_column', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', 'EXPERIMENTAL', name='kdc_field_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['kdc_asset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_version_id', 'field_name', name='uq_kdc_schema_fields_asset_version_field')
    )
    op.create_index('ix_kdc_schema_fields_field_name', 'kdc_schema_fields', ['field_name'], unique=False)
    op.create_index('ix_kdc_schema_fields_is_link_key', 'kdc_schema_fields', ['is_link_key'], unique=False)
    op.create_index('ix_kdc_schema_fields_semantics', 'kdc_schema_fields', ['semantics'], unique=False)
    op.create_index('ix_kdc_schema_fields_status', 'kdc_schema_fields', ['status'], unique=False)
    op.create_table('kdc_schemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_version_id', sa.Integer(), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('primary_key', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('link_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['kdc_asset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_version_id')
    )
    op.create_index('ix_kdc_schemas_asset_version_id', 'kdc_schemas', ['asset_version_id'], unique=False)
    op.create_index('ix_kdc_schemas_schema_hash', 'kdc_schemas', ['schema_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kdc_schemas_schema_hash', table_name='kdc_schemas')
    op.drop_index('ix_kdc_schemas_asset_version_id', table_name='kdc_schemas')
    op.drop_table('kdc_schemas')
    op.drop_index('ix_kdc_schema_fields_status', table_name='kdc_schema_fields')
    op.drop_index('ix_kdc_schema_fields_semantics', table_name='kdc_schema_fields')
    op.drop_index('ix_kdc_schema_fields_is_link_key', table_name='kdc_schema_fields')
    op.drop_index('ix_kdc_schema_fields_field_name', table_name='kdc_schema_fields')
    op.drop_table('kdc_schema_fields')
    op.drop_index('ix_kdc_lineages_parameters_hash', table_name='kdc_lineages')
    op.drop_index('ix_kdc_lineages_dtp_name', table_name='kdc_lineages')
    op.drop_table('kdc_lineages')
    op.drop_index('ix_kdc_asset_versions_status', table_name='kdc_asset_versions')
    op.drop_index('ix_kdc_asset_versions_asset_release', table_name='kdc_asset_versions')
    op.drop_index('ix_kdc_asset_versions_assembly', table_name='kdc_asset_versions')
    op.drop_table('kdc_asset_versions')
    op.drop_index('ix_kdc_scan_runs_status', table_name='kdc_scan_runs')
    op.drop_index('ix_kdc_scan_runs_started_at', table_name='kdc_scan_runs')
    op.drop_table('kdc_scan_runs')
    op.drop_index('ix_kdc_assets_source_system', table_name='kdc_assets')
    op.drop_index('ix_kdc_assets_data_source', table_name='kdc_assets')
    op.drop_index('ix_kdc_assets_asset', table_name='kdc_assets')
    op.drop_table('kdc_assets')
    # ### end Alembic commands ###
