[database]
db_uri = "postgresql+psycopg2://bioadmin:bioadmin@localhost/biofilter_dev"
echo_sql = false
auto_create = false

[etl]
data_root = "./biofilter_data"
allow_parallel = true
max_workers = 8

[reports]
default_output_format = "dataframe"
warn_on_empty = true

[logging]
level = "INFO"
log_to_file = true
log_file = "./biofilter.log"
