[database]
db_uri = "postgresql+psycopg2://admin:admin@localhost/biofilter_dev"
db_uri_local = "postgresql+psycopg2://admin:admin@localhost/biofilter_dev"
db_uri_vps = "postgresql+psycopg2://bioadmin:bioadmin@127.0.0.1:5432/biofilter_dev"
db_uri_vps_external = "postgresql+psycopg2://bioadmin:bioadmin@109.199.114.191:5432/biofilter_prod"
echo_sql = false
auto_create = false

[etl]
data_root = "./biofilter_data"
allow_parallel = true
max_workers = 8

[reports]
default_output_format = "dataframe"
warn_on_empty = true

[logging]
level = "INFO"
log_to_file = true
log_file = "./biofilter.log"
