from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from biofilter.modules.db.base import Base


class ChemicalMaster(Base):
    """
    Canonical representation of chemicals in Biofilter3R.

    Each chemical is linked to a unique Biofilter Entity (`entity_id`)
    and identified by a ChEBI accession (CHEBI:xxxx).
    The description provides a human-readable definition.
    Provenance is tracked via DataSource and ETLPackage.

    Relationships:
        - entity: Unique entity representation for the chemical
        - chemical_data: One-to-one physical/chemical properties
        - aliases: EntityAlias for synonyms/cross-references
    """

    __tablename__ = "chemical_masters"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # CHEBI ID (e.g., CHEBI:1234)
    chemical_id = Column(String(50), nullable=False, index=True, unique=True)

    # Canonical label
    name = Column(String(1000), nullable=True)

    # Optional definition from ChEBI
    definition = Column(Text, nullable=True)

    # # ASCII-only version of name
    # ascii_name = Column(String(255), nullable=True)

    # Formula string (e.g., C6H12O6)
    formula = Column(String(100), nullable=True)

    # Net charge
    charge = Column(Integer, nullable=True)

    # Average molecular mass
    mass = Column(Float, nullable=True)

    # Monoisotopic mass
    monoisotopic_mass = Column(Float, nullable=True)

    # Optional structure reference (FK to structures.tsv, future)
    structure_id = Column(Integer, nullable=True)
    # structure_id = Column(BigInteger, nullable=True)

    # Flag for autogenerated records
    is_autogenerated = Column(Boolean, nullable=True)

    # Status (active/obsolete/merged)
    omic_status_id = Column(
        Integer,
        ForeignKey("omic_status.id", ondelete="SET NULL"),
        nullable=True,
    )
    omic_status = relationship("OmicStatus")

    # Links to the central Entity table
    entity_id = Column(
        BigInteger, ForeignKey("entities.id", ondelete="CASCADE"), nullable=False  # noqa E501
    )
    entity = relationship("Entity", passive_deletes=True)

    # Provenance
    data_source_id = Column(
        Integer,
        ForeignKey("etl_data_sources.id", ondelete="CASCADE"),
        nullable=True,
    )
    data_source = relationship("ETLDataSource", passive_deletes=True)

    etl_package_id = Column(
        Integer,
        ForeignKey("etl_packages.id", ondelete="CASCADE"),
        nullable=True,
    )
    etl_package = relationship("ETLPackage", passive_deletes=True)
