# biofilter/modules/db/core_ddl.py


def ddl_list_partitions(
    parent_table: str,
    part_prefix: str,
    chrom_min: int = 1,
    chrom_max: int = 25,
) -> list[str]:
    ddls: list[str] = []
    for chrom in range(chrom_min, chrom_max + 1):
        part_name = f"{part_prefix}_chr_{chrom}"
        ddls.append(
            f"""
            CREATE TABLE IF NOT EXISTS {part_name}
            PARTITION OF {parent_table}
            FOR VALUES IN ({chrom});
            """.strip()
        )
    return ddls


def ddl_variant_masters() -> str:
    return """
    CREATE TABLE IF NOT EXISTS variant_masters (
        chromosome integer NOT NULL,
        variant_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,

        position_start bigint NOT NULL,
        position_end   bigint NOT NULL,

        reference_allele varchar(64) NOT NULL,
        alternate_allele varchar(256) NOT NULL,

        rsid varchar(32) NULL,

        variant_type varchar(20) NULL,
        allele_type  varchar(20) NULL,

        ac bigint NULL,
        an bigint NULL,
        af double precision NULL,
        grpmax varchar(32) NULL,
        grpmax_af double precision NULL,

        cadd_raw_score double precision NULL,
        cadd_phred double precision NULL,
        revel_max double precision NULL,

        spliceai_ds_max double precision NULL,
        pangolin_largest_ds double precision NULL,

        sift_max double precision NULL,
        polyphen_max double precision NULL,

        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_masters PRIMARY KEY (chromosome, variant_id),

        CONSTRAINT uq_variant_masters_natkey UNIQUE
            (chromosome, position_start, position_end, reference_allele, alternate_allele),

        CONSTRAINT ck_variant_masters_pos CHECK (position_end >= position_start),
        CONSTRAINT ck_variant_masters_af CHECK (af IS NULL OR (af >= 0.0 AND af <= 1.0)),
        CONSTRAINT ck_variant_masters_ac_an CHECK (
            (ac IS NULL AND an IS NULL)
            OR (ac IS NOT NULL AND an IS NOT NULL AND ac >= 0 AND an >= 0 AND ac <= an)
        )
    ) PARTITION BY LIST (chromosome);
    """.strip()


def ddl_variant_molecular_effect() -> str:
    return """
    CREATE TABLE IF NOT EXISTS variant_molecular_effects (
        chromosome integer NOT NULL,
        variant_id bigint NOT NULL,
        variant_key varchar(256) NOT NULL,

        -- Raw VEP identity / context
        gene_id varchar(32) NULL,             -- stable/raw gene id (e.g. ENSG...)
        gene_symbol varchar(64) NULL,         -- raw symbol from VEP for now
        transcript_id varchar(32) NOT NULL,   -- e.g. ENST...
        feature_type varchar(32) NULL,        -- Transcript, RegulatoryFeature, MotifFeature, etc.

        -- Raw consequence preserved
        consequence_raw varchar(255) NULL,    -- e.g. intron_variant&non_coding_transcript_variant

        -- Normalized consequence layers
        consequence_id integer NOT NULL,
        impact_id integer NULL,
        biotype_id integer NULL,
        consequence_group_id integer NULL,
        consequence_category_id integer NULL,

        -- Derived severity helpers
        consequence_rank integer NULL,
        impact_rank integer NULL,
        is_most_severe_for_annotation boolean NULL,
        is_most_severe_for_variant boolean NULL,

        -- Optional denormalized helpers for easier reporting/debug
        most_severe_consequence_per_annotation_id integer NULL,
        most_severe_consequence_per_variant_id integer NULL,

        -- Useful VEP context
        canonical boolean NULL,
        mane_select boolean NULL,
        mane_plus_clinical boolean NULL,

        -- HGVS / protein context
        hgvsc varchar(128) NULL,
        hgvsp varchar(128) NULL,
        cdna_position varchar(32) NULL,
        cds_position varchar(32) NULL,
        protein_position varchar(32) NULL,
        amino_acids varchar(32) NULL,
        codons varchar(64) NULL,
        ensp varchar(32) NULL,

        -- LoF / LOFTEE
        lof_flag boolean NULL,
        lof_confidence varchar(8) NULL,
        lof_filter varchar(128) NULL,
        lof_flags varchar(256) NULL,
        lof_info text NULL,

        -- Provenance
        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_molecular_effects PRIMARY KEY
            (chromosome, variant_id, transcript_id, consequence_id),

        CONSTRAINT ck_vme_lof_conf CHECK (
            lof_confidence IS NULL OR lof_confidence IN ('HC', 'LC', 'Filtered', 'NA')
        )
    ) PARTITION BY LIST (chromosome);
    """.strip()


def ddl_variant_effect_predictions() -> str:
    return """
    CREATE TABLE IF NOT EXISTS variant_effect_predictions (
        chromosome integer NOT NULL,
        variant_id bigint NOT NULL,

        -- Key to allow transcript_id nullable while preserving a strict PK
        predictor_key varchar(128) NOT NULL,  -- e.g. "cadd:v1:-" or "alphamissense:v1:ENST..."

        transcript_id varchar(32) NULL,       -- nullable for variant-level predictors

        predictor_name varchar(64) NOT NULL,  -- alphamissense/spliceai/pangolin/cadd/clinvar/...
        predictor_version varchar(32) NULL,

        score double precision NULL,
        classification varchar(64) NULL,      -- e.g. Pathogenic/Benign/HC/LC/...
        details text NULL,                    -- optional JSON/text blob for extra fields

        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_effect_predictions PRIMARY KEY
            (chromosome, variant_id, predictor_key)

    ) PARTITION BY LIST (chromosome);
    """.strip()


def ddl_variant_regulatory_elements() -> str:
    return """
    CREATE TABLE IF NOT EXISTS variant_regulatory_elements (
        chromosome integer NOT NULL,
        variant_id bigint NOT NULL,

        reg_element_key varchar(192) NOT NULL,       -- "regulatory_element_id:{bio_context or '-'}"

        regulatory_element_id varchar(64) NOT NULL,  -- e.g. ENCODE id, Ensembl regulatory feature id, etc.
        element_type varchar(32) NULL,               -- enhancer/promoter/TFBS/...
        bio_context varchar(128) NULL,               -- tissue/cell-type/assay context (string for now)

        score double precision NULL,
        details text NULL,

        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_regulatory_elements PRIMARY KEY
            (chromosome, variant_id, reg_element_key)

    ) PARTITION BY LIST (chromosome);
    """.strip()


def ddl_variant_gene_regulatory_evidence() -> str:
    return """
    CREATE TABLE IF NOT EXISTS variant_gene_regulatory_evidence (
        chromosome integer NOT NULL,
        variant_id bigint NOT NULL,

        evidence_key varchar(256) NOT NULL,     -- "gene_id:qtl_type:{bio_context or '-'}"

        gene_id varchar(32) NOT NULL,           -- ENSG... (string for now)
        bio_context varchar(128) NULL,          -- tissue/cell-type (string for now)
        qtl_type varchar(16) NOT NULL,          -- eQTL / sQTL / pQTL / caQTL ...

        beta double precision NULL,
        se double precision NULL,
        p_value double precision NULL,
        n integer NULL,

        effect_allele varchar(64) NULL,         -- optional

        details text NULL,

        data_source_id integer NULL,
        etl_package_id integer NULL,

        CONSTRAINT pk_variant_gene_regulatory_evidence PRIMARY KEY
            (chromosome, variant_id, evidence_key),

        CONSTRAINT ck_vgre_p CHECK (p_value IS NULL OR (p_value >= 0.0 AND p_value <= 1.0))
    ) PARTITION BY LIST (chromosome);
    """.strip()
