from .config_models import SystemConfig

from .omics_models import Gene, GeneGroup
from .etl_models import DataSource, SourceSystem, ETLProcess, ETLLog
from .entity_models import (
    EntityGroup,
    Entity,
    EntityName,
    RelationshipType,
    EntityRelationship,
)

# from .loki_models import (
#     Setting,
#     GrchUcschg,
#     LdProfile,
#     Namespace,
#     Relationship,
#     Role,
#     Source,
#     SourceOption,
#     SourceFile,
#     Type,
#     Warning,
#     SnpMerge,
#     SnpLocus,
#     SnpEntrezRole,
#     SnpBiopolymerRole,
#     Biopolymer,
#     BiopolymerName,
#     BiopolymerNameName,
#     BiopolymerRegion,
#     BiopolymerZone,
#     Group,
#     GroupName,
#     GroupGroup,
#     GroupBiopolymer,
#     GroupMemberName,
#     Gwas,
#     Chain,
#     ChainData,
# )

__all__ = [
    # # CONFIGURATION MODELS
    "SystemConfig",
    # # OMICS MODELS
    "GeneGroup",
    "Gene",
    # # ETL MODELS
    "SourceSystem",
    "DataSource",
    "ETLProcess",
    "ETLLog",
    # # ENTITY MODELS
    "EntityGroup",
    "Entity",
    "EntityName",
    "RelationshipType",
    "EntityRelationship",
    # # LOKI-LEGACY
    # "Setting",
    # "GrchUcschg",
    # "LdProfile",
    # "Namespace",
    # "Relationship",
    # "Role",
    # "Source",
    # "SourceOption",
    # "SourceFile",
    # "Type",
    # "Warning",
    # "SnpMerge",
    # "SnpLocus",
    # "SnpEntrezRole",
    # "SnpBiopolymerRole",
    # "Biopolymer",
    # "BiopolymerName",
    # "BiopolymerNameName",
    # "BiopolymerRegion",
    # "BiopolymerZone",
    # "Group",
    # "GroupName",
    # "GroupGroup",
    # "GroupBiopolymer",
    # "GroupMemberName",
    # "Gwas",
    # "Chain",
    # "ChainData",
]
