from .config_models import SystemConfig

from .omics_models import Gene
from .etl_models import DataSource, SourceSystem, ETLProcess
from .loki_models import (
    Setting,
    GrchUcschg,
    LdProfile,
    Namespace,
    Relationship,
    Role,
    Source,
    SourceOption,
    SourceFile,
    Type,
    Warning,
    SnpMerge,
    SnpLocus,
    SnpEntrezRole,
    SnpBiopolymerRole,
    Biopolymer,
    BiopolymerName,
    BiopolymerNameName,
    BiopolymerRegion,
    BiopolymerZone,
    Group,
    GroupName,
    GroupGroup,
    GroupBiopolymer,
    GroupMemberName,
    Gwas,
    Chain,
    ChainData,
)

__all__ = [
    "SystemConfig",
    "Gene",
    # "OmicsRelationship",
    # "OmicsTermAlternative",
    "DataSource",
    "ETLProcess",
    "SourceSystem",
    # LOKI-LEGACY
    "Setting",
    "GrchUcschg",
    "LdProfile",
    "Namespace",
    "Relationship",
    "Role",
    "Source",
    "SourceOption",
    "SourceFile",
    "Type",
    "Warning",
    "SnpMerge",
    "SnpLocus",
    "SnpEntrezRole",
    "SnpBiopolymerRole",
    "Biopolymer",
    "BiopolymerName",
    "BiopolymerNameName",
    "BiopolymerRegion",
    "BiopolymerZone",
    "Group",
    "GroupName",
    "GroupGroup",
    "GroupBiopolymer",
    "GroupMemberName",
    "Gwas",
    "Chain",
    "ChainData",
]
